import './globals.css'

import SiteNavBar from '@/components/SiteNavBar'
import Footer from '@/components/Footer'


export const metadata = {
  title: 'Agency Web Application',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='font-body bg-white'>
        <div className="bg-white text-black">
          <SiteNavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
